# Generated by Django 5.1.3 on 2024-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('funcao', models.CharField(choices=[('gomeiro', 'Gomeiro(a)'), ('forneiro', 'Forneiro(a)'), ('raspadeiro', 'Raspadeiro(a)')], max_length=60, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
