# Generated by Django 5.1.3 on 2024-12-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('funcao', models.CharField(choices=[('Gomeiro(a)', 'Gomeiro(a)'), ('Forneiro(a)', 'Forneiro(a)'), ('Raspadeiro(a)', 'Raspadeiro(a)')], max_length=60, verbose_name='Função')),
                ('preco_trabalho', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Preço do Trabalho')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('data', models.DateField(verbose_name='Dia da Produção')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
            },
        ),
    ]
