# Generated by Django 5.1.3 on 2024-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('Gomeiro(a)', 'Gomeiro(a)'), ('Forneiro(a)', 'Forneiro(a)'), ('Raspadeiro(a)', 'Raspadeiro(a)')], max_length=60, verbose_name='Função'),
        ),
    ]
