# Generated by Django 5.1.3 on 2024-12-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['-data'], 'verbose_name': 'Produção', 'verbose_name_plural': 'Produções'},
        ),
    ]
