# Generated by Django 5.1.3 on 2024-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('unidade', models.CharField(choices=[('Kg', 'Kg'), ('Un', 'Un')], max_length=100, verbose_name='Unidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
