# Generated by Django 5.1.3 on 2024-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastoinsumo',
            options={'verbose_name': 'Gasto de Insumo', 'verbose_name_plural': 'Gastos de Insumos'},
        ),
        migrations.AlterModelOptions(
            name='pagamentofuncionario',
            options={'verbose_name': 'Pagamento de Funcionário', 'verbose_name_plural': 'Pagamentos de Funcionários'},
        ),
    ]
